sudo:required
services:
        - docker
before_install:
        - docker build -t saimothkur1/docker-react -f Dockerfile.dev . 
script:
        - docker run -e CI=true saimothkur1/docker-react npm run test

          abcdef
